config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'post/vote/:id' => 'posts#vote', as: :post_vote
  get 'post/detail/:id' => 'posts#detail', as: :post_detail
  root 'pages#home'
  get 'login', to: 'login#index'
  post 'logout', to: 'login#logout', as: :logout_path
  get '/users/:id/finish_signup' => 'users#show_finish_signup', :as => :show_finish_signup
  patch '/users/:id/finish_signup' => 'users#finish_signup', :as => :finish_signup

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # We have introduced some convoluted logic in order to get email addess from twitter users
  # see http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/#completing-the-signup-process
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :twitter]

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  has_many :comments

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: auth.extra.raw_info.name,
                           provider: auth.provider,
                           uid: auth.uid,
                           email: auth.info.email,
                           password: Devise.friendly_token[0, 20],
        )
      end
    end
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      #twitter's api does not provide user's email address, so cannot check user's existence from email
      user = User.create(name: auth.info.name,
                           provider: auth.provider,
                           uid: auth.uid,
                           email: "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
                           password: Devise.friendly_token[0, 20],
        )
    end
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def logout

  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      set_flash_message(:notice, :failure, :kind => "Facebook") if is_navigational_format?
      redirect_to new_user_session_path and return
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    else
      set_flash_message(:error,  @user.errors.empty? ? "Error" : @user.errors.full_messages.to_sentence, :kind => "Twitter") if is_navigational_format?
      redirect_to new_user_session_path and return
    end
  end


  def after_sign_in_path_for(resource)
    #this is called by OmniauthCallbacksController in sign_in_and_redirect
    #since twitter does not provide an email address, for new twitter users we want to redirect to users#show_finish_signup
    #resource will be user
    if resource.email_verified?
      super resource
    else
      show_finish_signup_path(resource)
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all.order(votes: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def vote
    post = Post.find(params[:id])
    post.update(votes: post.votes.to_i + 1)
    render json: {post_id: post.id, total_votes: post.votes.to_s}
  end

  def detail
    @post = Post.find(params[:id])
    render partial: 'post_detail', layout: false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # We have introduced some convoluted logic in order to get email addess from twitter users
  # see http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/#completing-the-signup-process

  def show_finish_signup

  end

  def finish_signup
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to :root, notice: 'Your profile was successfully updated.'
    else
      flash[:error] = @user.errors.empty? ? "Error" : @user.errors.full_messages.to_sentence if is_navigational_format?
      redirect_to finish_signup_path(@user) and return
    end
  end

  private

  def user_params
    accessible = [:email]
    accessible << [:password, :password_confirmation] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.haml
!!! 5
%head
  %title HealthFundIt
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  .navbar.navbar-inverse.navbar-fixed-top
    .container
      .navbar-header
        = link_to 'HealthFundIt', root_path, class: 'navbar-brand'
      .collapse.navbar-collapse.navbar-ex1-collapse
        %ul.nav.navbar-nav
          %li{class: @page == :crowd_review ? 'active' : ''}= link_to 'Crowd Review', root_path
          %li{class: @page == :discover ? 'active' : ''}= link_to 'Discover', root_path
          %li{class: @page == :how_it_works ? 'active' : ''}= link_to 'How it Works', root_path
          %li{class: @page == :start ? 'active' : ''}= link_to 'Start', root_path
        %ul.nav.navbar-nav.pull-right
          - if user_signed_in?
            %li= link_to current_user.name, root_path
            %li= link_to('Logout', destroy_user_session_path, :method => :delete)
          - else
            %li{class: @page == :login ? 'active' : ''}= link_to 'Login', new_user_session_path


  .container.main
    = render 'layouts/messages'
    = yield

  = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/login/index.html.erb
<div class="container">


  <div class="omb_login">
    <h3 class="omb_authTitle">Login or <a href="#">Sign up</a></h3>
    <div class="row omb_row-sm-offset-3 omb_socialButtons">
      <div class="col-xs-4 col-sm-2">
        <a href="<%= user_omniauth_authorize_path(:facebook)%>" class="btn btn-lg btn-block omb_btn-facebook">
          <i class="fa fa-facebook visible-xs"></i>
          <span class="hidden-xs">Facebook</span>
       </a>
      </div>
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-twitter">
          <i class="fa fa-twitter visible-xs"></i>
          <span class="hidden-xs">Twitter</span>
        </a>
      </div>
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-google">
          <i class="fa fa-google-plus visible-xs"></i>
          <span class="hidden-xs">Google+</span>
        </a>
      </div>
    </div>

    <div class="row omb_row-sm-offset-3 omb_loginOr">
      <div class="col-xs-12 col-sm-6">
        <hr class="omb_hrOr">
        <span class="omb_spanOr">or</span>
      </div>
    </div>

    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
        <form class="omb_loginForm" action="" autocomplete="off" method="POST">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i></span>
            <input type="text" class="form-control" name="username" placeholder="email address">
          </div>
          <span class="help-block"></span>

          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
            <input  type="password" class="form-control" name="password" placeholder="Password">
          </div>
          <span class="help-block">Password error</span>

          <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        </form>
      </div>
    </div>
    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-3">
        <label class="checkbox">
          <input type="checkbox" value="remember-me">Remember Me
        </label>
      </div>
      <div class="col-xs-12 col-sm-3">
        <p class="omb_forgotPwd">
          <a href="#">Forgot password?</a>
        </p>
      </div>
    </div>
  </div>



</div>

app/views/pages/crowd-review.html.haml
- @page = :crowd_review

%h3 Crowd Review
%p= Faker::Lorem.paragraph

app/views/pages/discover.html.haml
- @page = :discover

%h3 Discover
%p= Faker::Lorem.paragraph

app/views/pages/home.html.haml
- @page = :home

.hero-unit
  %h1 Discover Today’s Cutting Edge Research
  %h3 Help advance tomorrow’s medical breakthroughs.

= render partial: @posts

app/views/pages/how-it-works.html.haml
- @page = :how_it_works

%h3 How it Works
%p= Faker::Lorem.paragraph

app/views/pages/login.html.haml
- @page = :login

%h3 Login
%p= Faker::Lorem.paragraph

app/views/pages/start.html.haml
- @page = :start

%h3 Start
%p= Faker::Lorem.paragraph

app/views/posts/_comment.html.haml
.comment
  = image_tag "avatars/#{comment.user.id}.jpg", width: '32', height: '32', align: 'left'
  %p{style: 'margin-bottom: 8px'}
    = link_to comment.user.name, '#'
    = comment.content

app/views/posts/_post.html.haml
.post
  .votes
    = link_to "", post_vote_path(post), :method => :post, :"data-type" => :json, :remote => true, :"data-post-id" => post.id, :authenticity_token => form_authenticity_token, class: 'vote glyphicon glyphicon-arrow-up'
    .vote #{post.votes.to_i}
  .blah
    .image
      = link_to image_tag(post.image_url, width: '284'), post_detail_path(post.id), data: {colorbox: true}
    .info
      .title= post.title
      .description= post.description
      .comments.pull-right= link_to "#{post.comments.count} comments", post_detail_path(post.id), data: {colorbox: true}
    .clearfix

app/views/posts/_post_detail.html.haml
.container.post-detail
  .row
    .col-md-8
      .image
        = image_tag @post.image_url
      .share{style: 'margin-top: 4px;'}
        = image_tag 'share.jpg'
      .description
        = GitHub::Markdown.render( @post.content  ).html_safe
    .col-md-4.right-side
      .row
        .col-md-9
          .title= @post.title
        .col-md-3.pull-right
          .vote
            = link_to "", post_vote_path(@post), :method => :post, :"data-type" => :json, :remote => true, :"data-post-id" => @post.id, :authenticity_token => form_authenticity_token, class: 'vote glyphicon glyphicon-arrow-up'
            %span.votes #{@post.votes.to_i}

      .post-comments
        = render partial: 'posts/comment', collection: @post.comments
      .new-comment
        %form{role: 'form'}
          = text_area_tag :new_comment, '', placeholder: 'Leave a Comment', rows: '5', class: 'form-control'
          = submit_tag 'Send', class: 'btn btn-success pull-right', style: 'margin-top: 5px;'

app/views/users/show_finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <div class="controls">
          <%= f.text_field :name, :autofocus => true, :value => '', class: 'form-control', placeholder: 'Example: email@me.com' %>
          <%= f.text_field :email, :value => '', class: 'form-control', placeholder: 'Your Name' %>
          <p class="help-block">Please confirm your email address and name. No spam.</p>
        </div>
      </div>
      <div class="actions">
        <%= f.submit 'Continue', :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>